title: Ballard In Motion
email: bdferris@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A project to document transportation infrastructure projects in the
  Ballard neighborhood of Seattle, WA.

baseurl: ""
url: ""

exclude:
  - Gemfile
  - Gemfile.lock
